### ISSUE TITLE
No group in 1st group phase and next.

### ISSUE THREAD

**Issue by saguas** [coactum/moodle-mod_discourse#6]
Hi. 

I setup a discourse activity. In configurations i have four groups and one student per group. My grouping name is ALL and i put all the four groups in this grouping. And the four groups appear in solo phase. 

In suma, in the solo phase it shows four groups. But in the other phases there are no group, it says "No groups available". I don't know why.

What i'am doing wrong?

**Note**: My Moodle version is 4.1.

<img width="1826" alt="Captura de ecrã 2023-01-11, às 08 38 23" src="https://user-images.githubusercontent.com/2410469/211757988-77156d8d-4eaa-407a-ad94-36ad8e2221b9.png">

**Comment by dtnolte** [comment]
Hello,
i think there is a little missunderstanding here: You dont have to create own groups and groupings, the discourse does this automatically when you add it to a course. At this moment, the plugin creates a grouping with groups for all phases and then takes all the participants enrolled in the course and automatically distributes them among the groups. Creating the groups by yourself is unfortunately not possible at the moment.
					
If you try to do this, you would have to assign specific group ID numbers so that they end up in the correct phases, but even then there would be complications.

So a better solution would be to work with the groups created by the discourse.

**Comment by saguas** [comment]
Hi Daniel. Thanks for your answer. I know that there is no need to create groups or groupings, but I try without create group or groupings and the plugins does not create any group.

**Comment by dtnolte** [comment]
Oh okay. But there were participants enrolled in the course when you created the discourse?

**Comment by saguas** [comment]
Yes. There were 30 students.

**Comment by dtnolte** [comment]
And did the discourse throw any error messages while you created it?

**Comment by saguas** [comment]
No.

**Comment by saguas** [comment]
I tried it in another classe and it created the group. I think the problem is solved. Thanks. By default my configuration set to groupings. I think that was the problem.

**Comment by dtnolte** [comment]
Happy to hear!
